sudo: required

services:
  - docker

language: node_js

node_js:
  - "6"

env:
  global:
    - CXX=g++-4.8
    - DOCKER_EMAIL=michael@laccetti.com
    - DOCKER_USERNAME=mlaccetti
    - secure: "hvK1mfw70HbQTzJrnoXpfVxXZhAx/Dl/wkskQGW/vLq1Jri3pl4oU4+7KK4QLvKJEPoZG/SM/FMquKEF2vbEip0v4JRAoQ+z8oUvCqfjFqkEPAmr9JYQ++9m7oykUeurQb4Px2rvqGRi1LKi4koglZh43K763ET+YZxuRxyH7AU0BVBRzYHMqnoWoNDQr/9VVyKQ6o52ej7wKUn3/6HgOqCXIQjXQytZhxhmnB5SoEN/VZaTOixaa7raeThslndFn+pkJo5hhKdlrpRtdj6a7QrBTjJjJzp8HDDcyWMsX+uXjEA8JPEYOtYXQyAC0gz6jIuMo+7JzHIhc0IsGx64Ln+9Qrc19Xj5S3wjqJUwu/zGH0CgTh8TyhQz6kWachbkssh00QlegNWLQz923D6oD7fsMhBr5EStR1t477H01nfAbpvDaiIk/ctjON5xFg4L/FGwLTcYFBNjDFiiEoEVY2biKnV/mmcT4U3i8nv+nk7i3wQu2F0bJxayRueVKy7ubjffmzxoDnYmkVOzh0aHo8VTvkBZzq33Rh+gYWW4bNudPaAmgov4sPIadO6wBqSsrQ3HliT/wY8pTgkNaFrMtI2JYEzvBoeaGnZQhBki1tKu7qiTOwQxf7KvmbQP9WNegWb9mCwh2sr2pmnbHYVmUQFz40HiCGlgtJ0h1IznfCQ="
    - secure: "JS0xd+JgYX9WtF7CnHsiPifRlGbRAw5qKs8pbQLtakCida9xwdYEdWQoRHolKjnY8PIGOcmdKVuEn3ehDuotmhIQet5obUK1O483JW+QMfSFSE6TI4/Bpr+yjZAbUqqaxsQAUVA2DtY87m3Jt9tbKuqWSnHttYJGf5BKIFsVfzQ2PAIEBPRA2LXub0AlNYVIXxfmaLs4bmGSs5UlrfZzhM2gqK8AjEL3UMhCvEMcXyFN+w2e3zH4cW0kQkgkHJy4MzRJihY0h2uT9zndZS55J2eOOzwMldKsgXEuV5q4yZpM9j06NwRZ/MuF4LFXu18mALRV1yIhgD3Hy6+gIeNcPVM9wg7uOp0UqULG6Hj8/mFzkKaCWiGIGxBG2o1HGYSpjl/agsw3tc0icuX/nedPTTSQuh4F0RSyXN8T7WgjE6D+VsM8H9y2JgtdMlAnNUXIMFv/Bf8qHTMXsGt4odhrfd/Lm2Lojgfm5PxHcSxvmAqkROyrg3kSMWClHcGbCpO9IhNYGkDfnFngyUt4Bl4Q7mnNaNK4bw4iICnwF1385jbhEpB+FiDpJ/Awgfeeevj+cwQ8m3mUViHp7v5oQ86Eq9EAvktWJpyEQmb6EMmzaLmhiAv0huLvxL5+wIWBn169759vBJYrtSzLqGhrFmTloLrauw8BSiM8S1x3Qrc9B3I="
  matrix:
    - NODE_ENV=development

cache:
  - apt: true
  - directories:
    - node_modules

addons:
  apt:
    packages:
    - build-essential
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - npm install -g gulp node-gyp codecov mr-doc

script:
  - npm install
  - npm update
  - gulp ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - docker login quay.io -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo "@gotglint:registry=https://registry.npmjs.org/" >> .npmrc
  - echo "//registry.npmjs.org/:_authToken=$NODE_TOKEN" >> .npmrc

deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true
