sudo: required

services:
  - docker

language: node_js

node_js:
  - "6"

env:
  global:
    - CXX=g++-4.8
    - DOCKER_EMAIL=michael@laccetti.com
    - DOCKER_USERNAME=mlaccetti
    - secure: hvK1mfw70HbQTzJrnoXpfVxXZhAx/Dl/wkskQGW/vLq1Jri3pl4oU4+7KK4QLvKJEPoZG/SM/FMquKEF2vbEip0v4JRAoQ+z8oUvCqfjFqkEPAmr9JYQ++9m7oykUeurQb4Px2rvqGRi1LKi4koglZh43K763ET+YZxuRxyH7AU0BVBRzYHMqnoWoNDQr/9VVyKQ6o52ej7wKUn3/6HgOqCXIQjXQytZhxhmnB5SoEN/VZaTOixaa7raeThslndFn+pkJo5hhKdlrpRtdj6a7QrBTjJjJzp8HDDcyWMsX+uXjEA8JPEYOtYXQyAC0gz6jIuMo+7JzHIhc0IsGx64Ln+9Qrc19Xj5S3wjqJUwu/zGH0CgTh8TyhQz6kWachbkssh00QlegNWLQz923D6oD7fsMhBr5EStR1t477H01nfAbpvDaiIk/ctjON5xFg4L/FGwLTcYFBNjDFiiEoEVY2biKnV/mmcT4U3i8nv+nk7i3wQu2F0bJxayRueVKy7ubjffmzxoDnYmkVOzh0aHo8VTvkBZzq33Rh+gYWW4bNudPaAmgov4sPIadO6wBqSsrQ3HliT/wY8pTgkNaFrMtI2JYEzvBoeaGnZQhBki1tKu7qiTOwQxf7KvmbQP9WNegWb9mCwh2sr2pmnbHYVmUQFz40HiCGlgtJ0h1IznfCQ=
  matrix:
    - NODE_ENV=development

cache:
  - apt: true
  - directories:
    - node_modules

addons:
  apt:
    packages:
    - build-essential
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - npm install -g gulp node-gyp codecov mr-doc

script:
  - gulp ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - docker login quay.io -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: npm
    email: michael@laccetti.com
    api_key:
      secure: C1yccYo1LKUy6RPaTdsio8kw5W9igcF8LACyfeBzt2vWv6tKt8NnNYVH/wVX4VVfq2gNcGv/xPlxFWHacblwG+yaiK0SaBL7A+xGO9wHZ1gZX/u3kRKc8dZqX0skvOufrAeUAYy35fxPs1u8GnSUSmrKe4x8ShvTt1gqTKCMWyBnnC9NKGcc+MK2rRmkxNSEUqHYy0PjVAQ5hv5Cj95jeruTAvH4OljQC6pDSOUccZ0/w7ggDDTQZkv37aYPp0RTxwqnA6yfxp6yGPoqCoffwPm0r3O4R1N/yPqh7lyqry7uf+6pICAe/bqq0G/ANAm06HP8CDJyRYQOhd/nlG9fpfktUj9lSqLJWy9s3fzoJ23pSFRFGjQdZyLy2X7tvJycPoZJn8dd2C2tEmTVbD699Hhf+/zN5bW87MzftUyvKI1r/lfk0CKSEQ7A4i1pn3f0AwVJ39Pgv+RbDvZh5h38DVWUI+DUBgSP0kndJYNjtXbjlmrx3EvoZ+R0X95PagJmYoIUOe1K0yWLlrJrKNFwqqTW/w6Hl0M69FtDR1XkePWuWnxK1ns0CvgjaGx+vA4u9SqtYpavxvnMVKf4gzTUAisYuXfTWOcuwkTMFnAMPhcjfx0Qfg+leeyto7xCZntTcWV6iDYOSDK9kjr7+X7txmUFG5fertRsnuAiYcUoRk8=
    on:
      tags: true
  - provider: script
    script: ./deploy.sh
    on:
      tags: true
