version: '2'

services:
  master:
    image: quay.io/glint/glint-cluster-master:latest
    ports:
     - "45468:45468"
  worker1:
    image: quay.io/glint/glint-cluster-worker:latest
    environment:
      - MASTER_HOST_IP=master
    links:
      - master
    depends_on:
      - master
  worker2:
    image: quay.io/glint/glint-cluster-worker:latest
    environment:
      - MASTER_HOST_IP=master
    links:
      - master
    depends_on:
      - master
